<?xml version="1.0" encoding="UTF-8"?>
<ncl id="test1">
  <body>
    <port id="p1" component="m1"/>
    <media id="m1" src="media/image1.png">
      <property name="depth" value="1.0"/>
      <property name="left" value="10%"/>
      <property name="top" value="10%"/>
      <property name="width" value="50%"/>
      <property name="height" value="50%"/>
    </media>   
  </body>
</ncl>

